url: https://wantsome.github.io
baseurl: ""

# Site settings
title: WantSome
email: getsome@wantsome.ro
description: "The friendly IT academy"


# Team names, titles and social links
people:
- name: Iuliana Anton
  pic: iuliana
  position: Co-Founder & Trainer
  social:
    - title: linkedin
      url: https://linkedin.com/in/iulianaanton
    - title: facebook
      url: https://www.facebook.com/anton.iuliana.gabriela

- name: Enciu Stoica
  pic: enciu
  position: Co-Founder & Trainer
  social:
    - title: linkedin
      url: https://linkedin.com/in/enciustoica
    - title: facebook
      url: https://www.facebook.com/enciu
    - title: twitter
      url: https://twitter.com/encius

- name: Ion Macari
  pic: ion
  position:  Trainer
  social:
    - title: linkedin
      url: https://linkedin.com/in/ionmacari
    - title: facebook
      url: #
    - title: twitter
      url: #

- name: Vali Popa
  pic: vali
  position: Trainer
  social:
    - title: linkedin
      url: https://linkedin.com/in/vapopa
    - title: facebook
      url: #
    - title: twitter
      url: #

- name: Liviu Costea
  pic: liviu
  position: Trainer
  social:
    - title: linkedin
      url: https://linkedin.com/in/liviucostea
    - title: facebook
      url: #
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/wantsome
  - title: facebook
    url: https://facebook.com/wantsome
  - title: github
    url: https://github.com/wantsomero/

# Postal address (add as many lines as necessary)
address:
  - line: Str. Voievozilor nr. 555
  - line: Iasi, Romania

# Build settings
markdown: kramdown
permalink: pretty
