url: http://www.wantsome.ro
baseurl: ""

# Site settings
title: Wantsome Iasi - The Friendly IT Academy
email: contact@wantsome.ro
description: "The Friendly IT Academy - cursuri de testare manuala, testare automata, dot net web development, java development, infrastracture engineer"

# Team names, titles and social links
people:
- name: Iuliana Anton
  pic: iuliana
  position: Co-Founder & Trainer
  social:
    - title: linkedin
      url: https://linkedin.com/in/iulianaanton
    - title: facebook
      url: https://www.facebook.com/anton.iuliana.gabriela

- name: Enciu Stoica
  pic: enciu
  position: Co-Founder & Trainer
  courses: ['testare-manuala','testare-automata']
  social:
    - title: linkedin
      url: https://linkedin.com/in/enciustoica
    - title: facebook
      url: https://www.facebook.com/enciu
    - title: twitter
      url: https://twitter.com/encius

- name: Ion Macari
  pic: ion
  position:  Trainer
  courses: ['testare-manuala']
  social:
    - title: linkedin
      url: https://linkedin.com/in/ionmacari
    - title: facebook
      url: #
    - title: twitter
      url: #

- name: Vali Popa
  pic: vali
  position: Trainer
  courses: ['testare-automata','testare-manuala']
  social:
    - title: linkedin
      url: https://linkedin.com/in/vapopa
    - title: facebook
      url: https://www.facebook.com/valipoparo
    - title: twitter
      url: https://twitter.com/valime

- name: Liviu Costea
  pic: liviu
  position: Trainer
  courses: ['dot-net']
  social:
    - title: linkedin
      url: https://linkedin.com/in/liviucostea
    - title: facebook
      url: #
    - title: twitter
      url: #

- name: Diana Sofian
  pic: diana
  position: Career Advisor
  social:
    - title: linkedin
      url: https://linkedin.com/in/diana-sofian-b4253989
    - title: facebook
      url: #
    - title: twitter
      url: #

- name: Bogdan Rusu
  pic: bogdan
  position: Trainer
  courses: ['testare-manuala']
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/bogdan-rusu-5288a43
    - title: facebook
      url: #
    - title: twitter
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/wantsomero
  - title: facebook
    url: https://facebook.com/wantsomeiasi
  - title: github
    url: https://github.com/wantsomero/

twitter_username: wantsomero
# Postal address (add as many lines as necessary)
address:
  - line: Str. Voievozilor nr. 555
  - line: Iasi, Romania

# Build settings
markdown: kramdown
permalink: /:title.html
gems:
  - jekyll-sitemap
