url: http://www.wantsome.ro
baseurl: ""

# Site settings
title: Wantsome Iasi - The Friendly IT Academy
email: contact@wantsome.ro
description: "The Friendly IT Academy - cursuri de testare manuala, testare automata, dot net web development, java development, infrastracture engineer"

# Team names, titles and social links
people:
- name: Iuliana Anton
  pic: iuliana
  position: Co-Founder & Trainer
  social:
    - title: linkedin
      url: https://linkedin.com/in/iulianaanton

- name: Enciu Stoica
  pic: enciu
  position: Co-Founder & Trainer
  courses: ['testare-manuala','testare-automata']
  social:
    - title: linkedin
      url: https://linkedin.com/in/enciustoica
    - title: twitter
      url: https://twitter.com/encius

- name: Ion Macari
  pic: ion
  position:  Trainer
  courses: ['testare-manuala']
  social:
    - title: linkedin
      url: https://linkedin.com/in/ionmacari

- name: Vali Popa
  pic: vali
  position: Trainer
  courses: ['testare-automata','testare-manuala']
  social:
    - title: linkedin
      url: https://linkedin.com/in/vapopa
    - title: twitter
      url: https://twitter.com/valime

- name: Liviu Costea
  pic: liviu
  position: Trainer
  courses: ['programare-dot-net']
  social:
    - title: linkedin
      url: https://linkedin.com/in/liviucostea
    - title: twitter
      url: clm160

- name: Diana Sofian
  pic: diana
  position: Career Advisor
  social:
    - title: linkedin
      url: https://linkedin.com/in/diana-sofian-b4253989

- name: Bogdan Rusu
  pic: bogdan
  position: Trainer
  courses: ['testare-manuala']
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/bogdan-rusu-5288a43

- name: Sebastian Ungureanu
  pic: sebastian
  position: Trainer
  courses: ['network-infrastructure']
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sebastian-ungureanu-89621215

- name: Michael Stoica
  pic: michael
  position: Trainer
  courses: ['network-infrastructure']
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/michaelstoica
    - title: twitter
      url: michaelstoica

- name: Ciprian Lipan
  pic: ciprian
  position: Trainer
  courses: ['programare-dot-net']
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ciprian-lipan-93a5b517/

- name: Eugen Anghel
  pic: eugen
  position: Trainer
  courses: ['programare-java']
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/eugenanghel/

- name: Răzvan Savel
  pic: razvan
  position: Trainer
  courses: ['testare-automata']
  social:
    - title: linkedin
      url: https://linkedin.com/in/razvansavel

- name: Răzvan Feidi
  pic: razvan_feidi
  position: Trainer
  courses: ['programare-java']
  social:
    - title: linkedin
      url: https://linkedin.com/in/razvan-feidi-49744a10

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/wantsomero
  - title: facebook
    url: https://facebook.com/wantsomeiasi
  - title: github
    url: https://github.com/wantsomero/

twitter_username: wantsomero
# Postal address (add as many lines as necessary)
address:
  - line: Str. Voievozilor nr. 555
  - line: Iasi, Romania

# Build settings
markdown: kramdown
permalink: /:title.html
gems:
  - jekyll-sitemap
